// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package userservice

import (
	"context"

	"sys/systemclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	InfoReq           = systemclient.InfoReq
	InfoResp          = systemclient.InfoResp
	LoginReq          = systemclient.LoginReq
	LoginResp         = systemclient.LoginResp
	ReSetPasswordReq  = systemclient.ReSetPasswordReq
	ReSetPasswordResp = systemclient.ReSetPasswordResp

	UserService interface {
		// 用户登录
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		// 获取用户个人信息
		UserInfo(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*InfoResp, error)
		// 重置用户密码
		ReSetPassword(ctx context.Context, in *ReSetPasswordReq, opts ...grpc.CallOption) (*ReSetPasswordResp, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

// 用户登录
func (m *defaultUserService) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := systemclient.NewUserServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// 获取用户个人信息
func (m *defaultUserService) UserInfo(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*InfoResp, error) {
	client := systemclient.NewUserServiceClient(m.cli.Conn())
	return client.UserInfo(ctx, in, opts...)
}

// 重置用户密码
func (m *defaultUserService) ReSetPassword(ctx context.Context, in *ReSetPasswordReq, opts ...grpc.CallOption) (*ReSetPasswordResp, error) {
	client := systemclient.NewUserServiceClient(m.cli.Conn())
	return client.ReSetPassword(ctx, in, opts...)
}
