// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package server

import (
	"context"

	"sys/internal/logic/userservice"
	"sys/internal/svc"
	"sys/systemclient"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	systemclient.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

// 用户登录
func (s *UserServiceServer) Login(ctx context.Context, in *systemclient.LoginReq) (*systemclient.LoginResp, error) {
	l := userservicelogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// 获取用户个人信息
func (s *UserServiceServer) UserInfo(ctx context.Context, in *systemclient.InfoReq) (*systemclient.InfoResp, error) {
	l := userservicelogic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}

// 重置用户密码
func (s *UserServiceServer) ReSetPassword(ctx context.Context, in *systemclient.ReSetPasswordReq) (*systemclient.ReSetPasswordResp, error) {
	l := userservicelogic.NewReSetPasswordLogic(ctx, s.svcCtx)
	return l.ReSetPassword(in)
}
