FROM alpine:3.18
#添加时区处理
RUN echo -e "https://mirrors.aliyun.com/alpine/v3.15/main\nhttps://mirrors.aliyun.com/alpine/v3.15/community"
 > /etc/apk/repositories && \
    apk update && \
    apk --no-cache add tzdata && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone \
 ENV TZ=Asia/Shanghai \
LABEL authors="define"

ARG SERVER_NAME=core
ARG SERVER_TYPE=rpc
ENV RUN_BIN bin/${SERVER_NAME}--${SERVER_TYPE}
ENV RUN_CONF /${SERVER_NAME}/conf${SERVER_TYPE}.yaml
#这个关键词的意思是复制的意思，可以将宿主机中的内容复制到容器中
#命令左边是宿主机的目录，右边是容器目录
RUN mkdir /$SERVER_NAME && mkdir /$SERVER_NAME/bin && mkdir /$SERVER_NAME/conf
# 复制编译后的二进制文件
COPY ./bin/$SERVER_NAME-$SERVER_TYPE /$SERVER_NAME/bin/
# 复制配置文件
COPY ./appS/$SERVER_NAME/$SERVER_TYPE/etc/$SERVER_NAME.yaml /$SERVER_NAME/Conf/
#为二进制提供执行权限
RUN chmod +X /$SERVER_NAME/bin/$SERVER_NAME-$SERVER_TYPE
# 该命令指定容器会默认进入那个目录，如我们每次进入服务器时会自动进入root目录一样作用
WORKDIR /$SERVER_NAME
ENTRYPOINT $RUN_BIN -f $RUN_CONF