// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: apps/admin/rpc/sys/proto/user.proto

package systemclient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 添加用户信息
type AddUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                     //用户id
	Mobile        string                 `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`                              //手机号码
	AccountName   string                 `protobuf:"bytes,3,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"` //用户账号
	NickName      string                 `protobuf:"bytes,4,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`          //用户昵称
	UserType      string                 `protobuf:"bytes,5,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`          //用户类型（00系统用户）
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`                              //头像路径
	Email         string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`                                //用户邮箱
	Password      string                 `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`                          //密码
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`                             //状态(1:正常，0:禁用)
	DeptId        int64                  `protobuf:"varint,10,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`              //部门ID
	Remark        string                 `protobuf:"bytes,11,opt,name=remark,proto3" json:"remark,omitempty"`                             //备注
	CreateName    string                 `protobuf:"bytes,12,opt,name=create_name,json=createName,proto3" json:"create_name,omitempty"`   //创建者名称
	CreateBy      string                 `protobuf:"bytes,13,opt,name=create_by,json=createBy,proto3" json:"create_by,omitempty"`         //创建者账号
	PostIds       []int64                `protobuf:"varint,14,rep,packed,name=PostIds,proto3" json:"PostIds,omitempty"`                   //岗位ids
	RoleIds       []int64                `protobuf:"varint,15,rep,packed,name=RoleIds,proto3" json:"RoleIds,omitempty"`                   //角色ids
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserReq) Reset() {
	*x = AddUserReq{}
	mi := &file_apps_admin_rpc_sys_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserReq) ProtoMessage() {}

func (x *AddUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_admin_rpc_sys_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserReq.ProtoReflect.Descriptor instead.
func (*AddUserReq) Descriptor() ([]byte, []int) {
	return file_apps_admin_rpc_sys_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *AddUserReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddUserReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *AddUserReq) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *AddUserReq) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *AddUserReq) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

func (x *AddUserReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *AddUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AddUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AddUserReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddUserReq) GetDeptId() int64 {
	if x != nil {
		return x.DeptId
	}
	return 0
}

func (x *AddUserReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *AddUserReq) GetCreateName() string {
	if x != nil {
		return x.CreateName
	}
	return ""
}

func (x *AddUserReq) GetCreateBy() string {
	if x != nil {
		return x.CreateBy
	}
	return ""
}

func (x *AddUserReq) GetPostIds() []int64 {
	if x != nil {
		return x.PostIds
	}
	return nil
}

func (x *AddUserReq) GetRoleIds() []int64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

// 更新用户信息
type UpdateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                     //用户id
	Mobile        string                 `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`                              //手机号码
	AccountName   string                 `protobuf:"bytes,3,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"` //用户账号
	NickName      string                 `protobuf:"bytes,4,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`          //用户昵称
	UserType      string                 `protobuf:"bytes,5,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`          //用户类型（00系统用户）
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`                              //头像路径
	Email         string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`                                //用户邮箱
	Password      string                 `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`                          //密码
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`                             //状态(1:正常，0:禁用)
	DeptId        int64                  `protobuf:"varint,10,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`              //部门ID
	Remark        string                 `protobuf:"bytes,11,opt,name=remark,proto3" json:"remark,omitempty"`                             //备注
	UpdateName    string                 `protobuf:"bytes,12,opt,name=update_name,json=updateName,proto3" json:"update_name,omitempty"`   //更新者名称
	UpdateBy      string                 `protobuf:"bytes,13,opt,name=update_by,json=updateBy,proto3" json:"update_by,omitempty"`         //更新者账号
	PostIds       []int64                `protobuf:"varint,14,rep,packed,name=PostIds,proto3" json:"PostIds,omitempty"`                   //岗位ids
	RoleIds       []int64                `protobuf:"varint,15,rep,packed,name=RoleIds,proto3" json:"RoleIds,omitempty"`                   //角色ids
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserReq) Reset() {
	*x = UpdateUserReq{}
	mi := &file_apps_admin_rpc_sys_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserReq) ProtoMessage() {}

func (x *UpdateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_admin_rpc_sys_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserReq.ProtoReflect.Descriptor instead.
func (*UpdateUserReq) Descriptor() ([]byte, []int) {
	return file_apps_admin_rpc_sys_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateUserReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UpdateUserReq) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *UpdateUserReq) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *UpdateUserReq) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

func (x *UpdateUserReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateUserReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateUserReq) GetDeptId() int64 {
	if x != nil {
		return x.DeptId
	}
	return 0
}

func (x *UpdateUserReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *UpdateUserReq) GetUpdateName() string {
	if x != nil {
		return x.UpdateName
	}
	return ""
}

func (x *UpdateUserReq) GetUpdateBy() string {
	if x != nil {
		return x.UpdateBy
	}
	return ""
}

func (x *UpdateUserReq) GetPostIds() []int64 {
	if x != nil {
		return x.PostIds
	}
	return nil
}

func (x *UpdateUserReq) GetRoleIds() []int64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

// 更新用户信息状态
type UpdateUserStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`                         //用户id
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`                          //状态(1:正常，0:禁用)
	UpdateName    string                 `protobuf:"bytes,3,opt,name=update_name,json=updateName,proto3" json:"update_name,omitempty"` //更新者名称
	UpdateBy      string                 `protobuf:"bytes,4,opt,name=update_by,json=updateBy,proto3" json:"update_by,omitempty"`       //更新者账号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserStatusReq) Reset() {
	*x = UpdateUserStatusReq{}
	mi := &file_apps_admin_rpc_sys_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserStatusReq) ProtoMessage() {}

func (x *UpdateUserStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_admin_rpc_sys_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateUserStatusReq) Descriptor() ([]byte, []int) {
	return file_apps_admin_rpc_sys_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserStatusReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *UpdateUserStatusReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateUserStatusReq) GetUpdateName() string {
	if x != nil {
		return x.UpdateName
	}
	return ""
}

func (x *UpdateUserStatusReq) GetUpdateBy() string {
	if x != nil {
		return x.UpdateBy
	}
	return ""
}

// 查询用户信息详情
type QueryUserDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUserDetailReq) Reset() {
	*x = QueryUserDetailReq{}
	mi := &file_apps_admin_rpc_sys_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUserDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUserDetailReq) ProtoMessage() {}

func (x *QueryUserDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_admin_rpc_sys_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUserDetailReq.ProtoReflect.Descriptor instead.
func (*QueryUserDetailReq) Descriptor() ([]byte, []int) {
	return file_apps_admin_rpc_sys_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *QueryUserDetailReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type QueryUserDetailResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                       //用户id
	Mobile           string                 `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`                                                //手机号码
	AccountName      string                 `protobuf:"bytes,3,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`                   //用户账号
	NickName         string                 `protobuf:"bytes,4,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`                            //用户昵称
	UserType         string                 `protobuf:"bytes,5,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`                            //用户类型（00系统用户）
	Avatar           string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`                                                //头像路径
	Email            string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`                                                  //用户邮箱
	Status           int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`                                               //状态(1:正常，0:禁用)
	DeptId           int64                  `protobuf:"varint,10,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`                                //部门ID
	LoginIp          string                 `protobuf:"bytes,11,opt,name=login_ip,json=loginIp,proto3" json:"login_ip,omitempty"`                              //最后登录IP
	LoginDateLast    string                 `protobuf:"bytes,12,opt,name=login_date_last,json=loginDateLast,proto3" json:"login_date_last,omitempty"`          //最后登录时间
	LoginBrowserType string                 `protobuf:"bytes,13,opt,name=login_browser_type,json=loginBrowserType,proto3" json:"login_browser_type,omitempty"` //浏览器类型
	LoginUserOs      string                 `protobuf:"bytes,14,opt,name=login_user_os,json=loginUserOs,proto3" json:"login_user_os,omitempty"`                //操作系统
	PwdUpdateDate    string                 `protobuf:"bytes,15,opt,name=pwd_update_date,json=pwdUpdateDate,proto3" json:"pwd_update_date,omitempty"`          //密码最后更新时间
	Remark           string                 `protobuf:"bytes,16,opt,name=remark,proto3" json:"remark,omitempty"`                                               //备注
	DelFlag          int32                  `protobuf:"varint,17,opt,name=del_flag,json=delFlag,proto3" json:"del_flag,omitempty"`                             //删除标志（0代表删除 1代表存在）
	CreateBy         string                 `protobuf:"bytes,18,opt,name=create_by,json=createBy,proto3" json:"create_by,omitempty"`                           //创建者
	CreateTime       string                 `protobuf:"bytes,19,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`                     //创建时间
	UpdateBy         string                 `protobuf:"bytes,20,opt,name=update_by,json=updateBy,proto3" json:"update_by,omitempty"`                           //更新者账号
	UpdateName       string                 `protobuf:"bytes,21,opt,name=update_name,json=updateName,proto3" json:"update_name,omitempty"`                     //更新者名称
	UpdateTime       string                 `protobuf:"bytes,22,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`                     //更新时间
	PostIds          []int64                `protobuf:"varint,23,rep,packed,name=PostIds,proto3" json:"PostIds,omitempty"`                                     //岗位ids
	RoleIds          []int64                `protobuf:"varint,24,rep,packed,name=RoleIds,proto3" json:"RoleIds,omitempty"`                                     //角色ids
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QueryUserDetailResp) Reset() {
	*x = QueryUserDetailResp{}
	mi := &file_apps_admin_rpc_sys_proto_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUserDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUserDetailResp) ProtoMessage() {}

func (x *QueryUserDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_admin_rpc_sys_proto_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUserDetailResp.ProtoReflect.Descriptor instead.
func (*QueryUserDetailResp) Descriptor() ([]byte, []int) {
	return file_apps_admin_rpc_sys_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *QueryUserDetailResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QueryUserDetailResp) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *QueryUserDetailResp) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *QueryUserDetailResp) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *QueryUserDetailResp) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

func (x *QueryUserDetailResp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *QueryUserDetailResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *QueryUserDetailResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *QueryUserDetailResp) GetDeptId() int64 {
	if x != nil {
		return x.DeptId
	}
	return 0
}

func (x *QueryUserDetailResp) GetLoginIp() string {
	if x != nil {
		return x.LoginIp
	}
	return ""
}

func (x *QueryUserDetailResp) GetLoginDateLast() string {
	if x != nil {
		return x.LoginDateLast
	}
	return ""
}

func (x *QueryUserDetailResp) GetLoginBrowserType() string {
	if x != nil {
		return x.LoginBrowserType
	}
	return ""
}

func (x *QueryUserDetailResp) GetLoginUserOs() string {
	if x != nil {
		return x.LoginUserOs
	}
	return ""
}

func (x *QueryUserDetailResp) GetPwdUpdateDate() string {
	if x != nil {
		return x.PwdUpdateDate
	}
	return ""
}

func (x *QueryUserDetailResp) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *QueryUserDetailResp) GetDelFlag() int32 {
	if x != nil {
		return x.DelFlag
	}
	return 0
}

func (x *QueryUserDetailResp) GetCreateBy() string {
	if x != nil {
		return x.CreateBy
	}
	return ""
}

func (x *QueryUserDetailResp) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *QueryUserDetailResp) GetUpdateBy() string {
	if x != nil {
		return x.UpdateBy
	}
	return ""
}

func (x *QueryUserDetailResp) GetUpdateName() string {
	if x != nil {
		return x.UpdateName
	}
	return ""
}

func (x *QueryUserDetailResp) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *QueryUserDetailResp) GetPostIds() []int64 {
	if x != nil {
		return x.PostIds
	}
	return nil
}

func (x *QueryUserDetailResp) GetRoleIds() []int64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

// 分页查询用户信息列表
type QueryUserListReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Mobile           string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`                                                //手机号码
	AccountName      string                 `protobuf:"bytes,2,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`                   //用户账号
	NickName         string                 `protobuf:"bytes,3,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`                            //用户昵称
	UserType         string                 `protobuf:"bytes,4,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`                            //用户类型（00系统用户）
	Avatar           string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`                                                //头像路径
	Email            string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`                                                  //用户邮箱
	Password         string                 `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`                                            //密码
	Status           int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`                                               //状态(1:正常，0:禁用)
	DeptId           int64                  `protobuf:"varint,9,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`                                 //部门ID
	LoginIp          string                 `protobuf:"bytes,10,opt,name=login_ip,json=loginIp,proto3" json:"login_ip,omitempty"`                              //最后登录IP
	LoginDateLast    string                 `protobuf:"bytes,11,opt,name=login_date_last,json=loginDateLast,proto3" json:"login_date_last,omitempty"`          //最后登录时间
	LoginBrowserType string                 `protobuf:"bytes,12,opt,name=login_browser_type,json=loginBrowserType,proto3" json:"login_browser_type,omitempty"` //浏览器类型
	LoginUserOs      string                 `protobuf:"bytes,13,opt,name=login_user_os,json=loginUserOs,proto3" json:"login_user_os,omitempty"`                //操作系统
	PwdUpdateDate    string                 `protobuf:"bytes,14,opt,name=pwd_update_date,json=pwdUpdateDate,proto3" json:"pwd_update_date,omitempty"`          //密码最后更新时间
	DelFlag          int32                  `protobuf:"varint,15,opt,name=del_flag,json=delFlag,proto3" json:"del_flag,omitempty"`                             //删除标志（0代表删除 1代表存在）
	PageNum          int64                  `protobuf:"varint,16,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`                             //第几页
	PageSize         int64                  `protobuf:"varint,17,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`                          //每页的数量
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QueryUserListReq) Reset() {
	*x = QueryUserListReq{}
	mi := &file_apps_admin_rpc_sys_proto_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUserListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUserListReq) ProtoMessage() {}

func (x *QueryUserListReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_admin_rpc_sys_proto_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUserListReq.ProtoReflect.Descriptor instead.
func (*QueryUserListReq) Descriptor() ([]byte, []int) {
	return file_apps_admin_rpc_sys_proto_user_proto_rawDescGZIP(), []int{5}
}

func (x *QueryUserListReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *QueryUserListReq) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *QueryUserListReq) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *QueryUserListReq) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

func (x *QueryUserListReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *QueryUserListReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *QueryUserListReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *QueryUserListReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *QueryUserListReq) GetDeptId() int64 {
	if x != nil {
		return x.DeptId
	}
	return 0
}

func (x *QueryUserListReq) GetLoginIp() string {
	if x != nil {
		return x.LoginIp
	}
	return ""
}

func (x *QueryUserListReq) GetLoginDateLast() string {
	if x != nil {
		return x.LoginDateLast
	}
	return ""
}

func (x *QueryUserListReq) GetLoginBrowserType() string {
	if x != nil {
		return x.LoginBrowserType
	}
	return ""
}

func (x *QueryUserListReq) GetLoginUserOs() string {
	if x != nil {
		return x.LoginUserOs
	}
	return ""
}

func (x *QueryUserListReq) GetPwdUpdateDate() string {
	if x != nil {
		return x.PwdUpdateDate
	}
	return ""
}

func (x *QueryUserListReq) GetDelFlag() int32 {
	if x != nil {
		return x.DelFlag
	}
	return 0
}

func (x *QueryUserListReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *QueryUserListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UserListData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                       //用户id
	Mobile           string                 `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`                                                //手机号码
	AccountName      string                 `protobuf:"bytes,3,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`                   //用户账号
	NickName         string                 `protobuf:"bytes,4,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`                            //用户昵称
	UserType         string                 `protobuf:"bytes,5,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`                            //用户类型（00系统用户）
	Avatar           string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`                                                //头像路径
	Email            string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`                                                  //用户邮箱
	Status           int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`                                               //状态(1:正常，0:禁用)
	DeptId           int64                  `protobuf:"varint,10,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`                                //部门ID
	LoginIp          string                 `protobuf:"bytes,11,opt,name=login_ip,json=loginIp,proto3" json:"login_ip,omitempty"`                              //最后登录IP
	LoginDateLast    string                 `protobuf:"bytes,12,opt,name=login_date_last,json=loginDateLast,proto3" json:"login_date_last,omitempty"`          //最后登录时间
	LoginBrowserType string                 `protobuf:"bytes,13,opt,name=login_browser_type,json=loginBrowserType,proto3" json:"login_browser_type,omitempty"` //浏览器类型
	LoginUserOs      string                 `protobuf:"bytes,14,opt,name=login_user_os,json=loginUserOs,proto3" json:"login_user_os,omitempty"`                //操作系统
	PwdUpdateDate    string                 `protobuf:"bytes,15,opt,name=pwd_update_date,json=pwdUpdateDate,proto3" json:"pwd_update_date,omitempty"`          //密码最后更新时间
	Remark           string                 `protobuf:"bytes,16,opt,name=remark,proto3" json:"remark,omitempty"`                                               //备注
	DelFlag          int32                  `protobuf:"varint,17,opt,name=del_flag,json=delFlag,proto3" json:"del_flag,omitempty"`                             //删除标志（0代表删除 1代表存在）
	CreateBy         string                 `protobuf:"bytes,18,opt,name=create_by,json=createBy,proto3" json:"create_by,omitempty"`                           //创建者账号
	CreateName       string                 `protobuf:"bytes,19,opt,name=create_name,json=createName,proto3" json:"create_name,omitempty"`                     //创建者名称
	CreateTime       string                 `protobuf:"bytes,20,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`                     //创建时间
	UpdateBy         string                 `protobuf:"bytes,21,opt,name=update_by,json=updateBy,proto3" json:"update_by,omitempty"`                           //更新者账号
	UpdateName       string                 `protobuf:"bytes,22,opt,name=update_name,json=updateName,proto3" json:"update_name,omitempty"`                     //更新者名称
	UpdateTime       string                 `protobuf:"bytes,23,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`                     //更新时间
	PostIds          []int64                `protobuf:"varint,24,rep,packed,name=PostIds,proto3" json:"PostIds,omitempty"`                                     //岗位ids
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserListData) Reset() {
	*x = UserListData{}
	mi := &file_apps_admin_rpc_sys_proto_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListData) ProtoMessage() {}

func (x *UserListData) ProtoReflect() protoreflect.Message {
	mi := &file_apps_admin_rpc_sys_proto_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListData.ProtoReflect.Descriptor instead.
func (*UserListData) Descriptor() ([]byte, []int) {
	return file_apps_admin_rpc_sys_proto_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserListData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserListData) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UserListData) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *UserListData) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *UserListData) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

func (x *UserListData) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserListData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserListData) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserListData) GetDeptId() int64 {
	if x != nil {
		return x.DeptId
	}
	return 0
}

func (x *UserListData) GetLoginIp() string {
	if x != nil {
		return x.LoginIp
	}
	return ""
}

func (x *UserListData) GetLoginDateLast() string {
	if x != nil {
		return x.LoginDateLast
	}
	return ""
}

func (x *UserListData) GetLoginBrowserType() string {
	if x != nil {
		return x.LoginBrowserType
	}
	return ""
}

func (x *UserListData) GetLoginUserOs() string {
	if x != nil {
		return x.LoginUserOs
	}
	return ""
}

func (x *UserListData) GetPwdUpdateDate() string {
	if x != nil {
		return x.PwdUpdateDate
	}
	return ""
}

func (x *UserListData) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *UserListData) GetDelFlag() int32 {
	if x != nil {
		return x.DelFlag
	}
	return 0
}

func (x *UserListData) GetCreateBy() string {
	if x != nil {
		return x.CreateBy
	}
	return ""
}

func (x *UserListData) GetCreateName() string {
	if x != nil {
		return x.CreateName
	}
	return ""
}

func (x *UserListData) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *UserListData) GetUpdateBy() string {
	if x != nil {
		return x.UpdateBy
	}
	return ""
}

func (x *UserListData) GetUpdateName() string {
	if x != nil {
		return x.UpdateName
	}
	return ""
}

func (x *UserListData) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *UserListData) GetPostIds() []int64 {
	if x != nil {
		return x.PostIds
	}
	return nil
}

type QueryUserListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*UserListData        `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUserListResp) Reset() {
	*x = QueryUserListResp{}
	mi := &file_apps_admin_rpc_sys_proto_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUserListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUserListResp) ProtoMessage() {}

func (x *QueryUserListResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_admin_rpc_sys_proto_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUserListResp.ProtoReflect.Descriptor instead.
func (*QueryUserListResp) Descriptor() ([]byte, []int) {
	return file_apps_admin_rpc_sys_proto_user_proto_rawDescGZIP(), []int{7}
}

func (x *QueryUserListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *QueryUserListResp) GetList() []*UserListData {
	if x != nil {
		return x.List
	}
	return nil
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`                      //账号
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`                    //密码
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`                            //验证码
	IpAddress     string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"` //IP地址
	Os            string                 `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`                                //操作系统
	Browser       string                 `protobuf:"bytes,6,opt,name=browser,proto3" json:"browser,omitempty"`                      //浏览器
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_apps_admin_rpc_sys_proto_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_admin_rpc_sys_proto_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_apps_admin_rpc_sys_proto_user_proto_rawDescGZIP(), []int{8}
}

func (x *LoginReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LoginReq) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *LoginReq) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *LoginReq) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	AccessToken   string                 `protobuf:"bytes,3,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"` //  repeated string ApiUrls = 4;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_apps_admin_rpc_sys_proto_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_admin_rpc_sys_proto_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_apps_admin_rpc_sys_proto_user_proto_rawDescGZIP(), []int{9}
}

func (x *LoginResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LoginResp) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *LoginResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type InfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoReq) Reset() {
	*x = InfoReq{}
	mi := &file_apps_admin_rpc_sys_proto_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoReq) ProtoMessage() {}

func (x *InfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_admin_rpc_sys_proto_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoReq.ProtoReflect.Descriptor instead.
func (*InfoReq) Descriptor() ([]byte, []int) {
	return file_apps_admin_rpc_sys_proto_user_proto_rawDescGZIP(), []int{10}
}

func (x *InfoReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type InfoResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Avatar         string                 `protobuf:"bytes,1,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BackgroundUrls []string               `protobuf:"bytes,3,rep,name=BackgroundUrls,proto3" json:"BackgroundUrls,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InfoResp) Reset() {
	*x = InfoResp{}
	mi := &file_apps_admin_rpc_sys_proto_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResp) ProtoMessage() {}

func (x *InfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_admin_rpc_sys_proto_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResp.ProtoReflect.Descriptor instead.
func (*InfoResp) Descriptor() ([]byte, []int) {
	return file_apps_admin_rpc_sys_proto_user_proto_rawDescGZIP(), []int{11}
}

func (x *InfoResp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *InfoResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InfoResp) GetBackgroundUrls() []string {
	if x != nil {
		return x.BackgroundUrls
	}
	return nil
}

type ReSetPasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UpdateBy      string                 `protobuf:"bytes,2,opt,name=update_by,json=updateBy,proto3" json:"update_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReSetPasswordReq) Reset() {
	*x = ReSetPasswordReq{}
	mi := &file_apps_admin_rpc_sys_proto_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReSetPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReSetPasswordReq) ProtoMessage() {}

func (x *ReSetPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_admin_rpc_sys_proto_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReSetPasswordReq.ProtoReflect.Descriptor instead.
func (*ReSetPasswordReq) Descriptor() ([]byte, []int) {
	return file_apps_admin_rpc_sys_proto_user_proto_rawDescGZIP(), []int{12}
}

func (x *ReSetPasswordReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReSetPasswordReq) GetUpdateBy() string {
	if x != nil {
		return x.UpdateBy
	}
	return ""
}

type ReSetPasswordResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pong          string                 `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReSetPasswordResp) Reset() {
	*x = ReSetPasswordResp{}
	mi := &file_apps_admin_rpc_sys_proto_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReSetPasswordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReSetPasswordResp) ProtoMessage() {}

func (x *ReSetPasswordResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_admin_rpc_sys_proto_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReSetPasswordResp.ProtoReflect.Descriptor instead.
func (*ReSetPasswordResp) Descriptor() ([]byte, []int) {
	return file_apps_admin_rpc_sys_proto_user_proto_rawDescGZIP(), []int{13}
}

func (x *ReSetPasswordResp) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

var File_apps_admin_rpc_sys_proto_user_proto protoreflect.FileDescriptor

const file_apps_admin_rpc_sys_proto_user_proto_rawDesc = "" +
	"\n" +
	"#apps/admin/rpc/sys/proto/user.proto\x12\fsystemclient\"\x96\x03\n" +
	"\n" +
	"AddUserReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06mobile\x18\x02 \x01(\tR\x06mobile\x12!\n" +
	"\faccount_name\x18\x03 \x01(\tR\vaccountName\x12\x1b\n" +
	"\tnick_name\x18\x04 \x01(\tR\bnickName\x12\x1b\n" +
	"\tuser_type\x18\x05 \x01(\tR\buserType\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\b \x01(\tR\bpassword\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12\x17\n" +
	"\adept_id\x18\n" +
	" \x01(\x03R\x06deptId\x12\x16\n" +
	"\x06remark\x18\v \x01(\tR\x06remark\x12\x1f\n" +
	"\vcreate_name\x18\f \x01(\tR\n" +
	"createName\x12\x1b\n" +
	"\tcreate_by\x18\r \x01(\tR\bcreateBy\x12\x18\n" +
	"\aPostIds\x18\x0e \x03(\x03R\aPostIds\x12\x18\n" +
	"\aRoleIds\x18\x0f \x03(\x03R\aRoleIds\"\x99\x03\n" +
	"\rUpdateUserReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06mobile\x18\x02 \x01(\tR\x06mobile\x12!\n" +
	"\faccount_name\x18\x03 \x01(\tR\vaccountName\x12\x1b\n" +
	"\tnick_name\x18\x04 \x01(\tR\bnickName\x12\x1b\n" +
	"\tuser_type\x18\x05 \x01(\tR\buserType\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\b \x01(\tR\bpassword\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12\x17\n" +
	"\adept_id\x18\n" +
	" \x01(\x03R\x06deptId\x12\x16\n" +
	"\x06remark\x18\v \x01(\tR\x06remark\x12\x1f\n" +
	"\vupdate_name\x18\f \x01(\tR\n" +
	"updateName\x12\x1b\n" +
	"\tupdate_by\x18\r \x01(\tR\bupdateBy\x12\x18\n" +
	"\aPostIds\x18\x0e \x03(\x03R\aPostIds\x12\x18\n" +
	"\aRoleIds\x18\x0f \x03(\x03R\aRoleIds\"}\n" +
	"\x13UpdateUserStatusReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x1f\n" +
	"\vupdate_name\x18\x03 \x01(\tR\n" +
	"updateName\x12\x1b\n" +
	"\tupdate_by\x18\x04 \x01(\tR\bupdateBy\"$\n" +
	"\x12QueryUserDetailReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xba\x05\n" +
	"\x13QueryUserDetailResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06mobile\x18\x02 \x01(\tR\x06mobile\x12!\n" +
	"\faccount_name\x18\x03 \x01(\tR\vaccountName\x12\x1b\n" +
	"\tnick_name\x18\x04 \x01(\tR\bnickName\x12\x1b\n" +
	"\tuser_type\x18\x05 \x01(\tR\buserType\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12\x17\n" +
	"\adept_id\x18\n" +
	" \x01(\x03R\x06deptId\x12\x19\n" +
	"\blogin_ip\x18\v \x01(\tR\aloginIp\x12&\n" +
	"\x0flogin_date_last\x18\f \x01(\tR\rloginDateLast\x12,\n" +
	"\x12login_browser_type\x18\r \x01(\tR\x10loginBrowserType\x12\"\n" +
	"\rlogin_user_os\x18\x0e \x01(\tR\vloginUserOs\x12&\n" +
	"\x0fpwd_update_date\x18\x0f \x01(\tR\rpwdUpdateDate\x12\x16\n" +
	"\x06remark\x18\x10 \x01(\tR\x06remark\x12\x19\n" +
	"\bdel_flag\x18\x11 \x01(\x05R\adelFlag\x12\x1b\n" +
	"\tcreate_by\x18\x12 \x01(\tR\bcreateBy\x12\x1f\n" +
	"\vcreate_time\x18\x13 \x01(\tR\n" +
	"createTime\x12\x1b\n" +
	"\tupdate_by\x18\x14 \x01(\tR\bupdateBy\x12\x1f\n" +
	"\vupdate_name\x18\x15 \x01(\tR\n" +
	"updateName\x12\x1f\n" +
	"\vupdate_time\x18\x16 \x01(\tR\n" +
	"updateTime\x12\x18\n" +
	"\aPostIds\x18\x17 \x03(\x03R\aPostIds\x12\x18\n" +
	"\aRoleIds\x18\x18 \x03(\x03R\aRoleIds\"\x92\x04\n" +
	"\x10QueryUserListReq\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12!\n" +
	"\faccount_name\x18\x02 \x01(\tR\vaccountName\x12\x1b\n" +
	"\tnick_name\x18\x03 \x01(\tR\bnickName\x12\x1b\n" +
	"\tuser_type\x18\x04 \x01(\tR\buserType\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\a \x01(\tR\bpassword\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\x17\n" +
	"\adept_id\x18\t \x01(\x03R\x06deptId\x12\x19\n" +
	"\blogin_ip\x18\n" +
	" \x01(\tR\aloginIp\x12&\n" +
	"\x0flogin_date_last\x18\v \x01(\tR\rloginDateLast\x12,\n" +
	"\x12login_browser_type\x18\f \x01(\tR\x10loginBrowserType\x12\"\n" +
	"\rlogin_user_os\x18\r \x01(\tR\vloginUserOs\x12&\n" +
	"\x0fpwd_update_date\x18\x0e \x01(\tR\rpwdUpdateDate\x12\x19\n" +
	"\bdel_flag\x18\x0f \x01(\x05R\adelFlag\x12\x19\n" +
	"\bpage_num\x18\x10 \x01(\x03R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x11 \x01(\x03R\bpageSize\"\xba\x05\n" +
	"\fUserListData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06mobile\x18\x02 \x01(\tR\x06mobile\x12!\n" +
	"\faccount_name\x18\x03 \x01(\tR\vaccountName\x12\x1b\n" +
	"\tnick_name\x18\x04 \x01(\tR\bnickName\x12\x1b\n" +
	"\tuser_type\x18\x05 \x01(\tR\buserType\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12\x17\n" +
	"\adept_id\x18\n" +
	" \x01(\x03R\x06deptId\x12\x19\n" +
	"\blogin_ip\x18\v \x01(\tR\aloginIp\x12&\n" +
	"\x0flogin_date_last\x18\f \x01(\tR\rloginDateLast\x12,\n" +
	"\x12login_browser_type\x18\r \x01(\tR\x10loginBrowserType\x12\"\n" +
	"\rlogin_user_os\x18\x0e \x01(\tR\vloginUserOs\x12&\n" +
	"\x0fpwd_update_date\x18\x0f \x01(\tR\rpwdUpdateDate\x12\x16\n" +
	"\x06remark\x18\x10 \x01(\tR\x06remark\x12\x19\n" +
	"\bdel_flag\x18\x11 \x01(\x05R\adelFlag\x12\x1b\n" +
	"\tcreate_by\x18\x12 \x01(\tR\bcreateBy\x12\x1f\n" +
	"\vcreate_name\x18\x13 \x01(\tR\n" +
	"createName\x12\x1f\n" +
	"\vcreate_time\x18\x14 \x01(\tR\n" +
	"createTime\x12\x1b\n" +
	"\tupdate_by\x18\x15 \x01(\tR\bupdateBy\x12\x1f\n" +
	"\vupdate_name\x18\x16 \x01(\tR\n" +
	"updateName\x12\x1f\n" +
	"\vupdate_time\x18\x17 \x01(\tR\n" +
	"updateTime\x12\x18\n" +
	"\aPostIds\x18\x18 \x03(\x03R\aPostIds\"Y\n" +
	"\x11QueryUserListResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12.\n" +
	"\x04list\x18\x02 \x03(\v2\x1a.systemclient.UserListDataR\x04list\"\x9d\x01\n" +
	"\bLoginReq\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12\x0e\n" +
	"\x02os\x18\x05 \x01(\tR\x02os\x12\x18\n" +
	"\abrowser\x18\x06 \x01(\tR\abrowser\"Y\n" +
	"\tloginResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\buserName\x18\x02 \x01(\tR\buserName\x12 \n" +
	"\vAccessToken\x18\x03 \x01(\tR\vAccessToken\"!\n" +
	"\aInfoReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\"^\n" +
	"\bInfoResp\x12\x16\n" +
	"\x06avatar\x18\x01 \x01(\tR\x06avatar\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x0eBackgroundUrls\x18\x03 \x03(\tR\x0eBackgroundUrls\"?\n" +
	"\x10ReSetPasswordReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tupdate_by\x18\x02 \x01(\tR\bupdateBy\"'\n" +
	"\x11ReSetPasswordResp\x12\x12\n" +
	"\x04pong\x18\x01 \x01(\tR\x04pong2\xd4\x01\n" +
	"\vUserService\x128\n" +
	"\x05Login\x12\x16.systemclient.LoginReq\x1a\x17.systemclient.loginResp\x129\n" +
	"\bUserInfo\x12\x15.systemclient.InfoReq\x1a\x16.systemclient.InfoResp\x12P\n" +
	"\rReSetPassword\x12\x1e.systemclient.ReSetPasswordReq\x1a\x1f.systemclient.ReSetPasswordRespB\x10Z\x0e./systemclientb\x06proto3"

var (
	file_apps_admin_rpc_sys_proto_user_proto_rawDescOnce sync.Once
	file_apps_admin_rpc_sys_proto_user_proto_rawDescData []byte
)

func file_apps_admin_rpc_sys_proto_user_proto_rawDescGZIP() []byte {
	file_apps_admin_rpc_sys_proto_user_proto_rawDescOnce.Do(func() {
		file_apps_admin_rpc_sys_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_admin_rpc_sys_proto_user_proto_rawDesc), len(file_apps_admin_rpc_sys_proto_user_proto_rawDesc)))
	})
	return file_apps_admin_rpc_sys_proto_user_proto_rawDescData
}

var file_apps_admin_rpc_sys_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_apps_admin_rpc_sys_proto_user_proto_goTypes = []any{
	(*AddUserReq)(nil),          // 0: systemclient.AddUserReq
	(*UpdateUserReq)(nil),       // 1: systemclient.UpdateUserReq
	(*UpdateUserStatusReq)(nil), // 2: systemclient.UpdateUserStatusReq
	(*QueryUserDetailReq)(nil),  // 3: systemclient.QueryUserDetailReq
	(*QueryUserDetailResp)(nil), // 4: systemclient.QueryUserDetailResp
	(*QueryUserListReq)(nil),    // 5: systemclient.QueryUserListReq
	(*UserListData)(nil),        // 6: systemclient.UserListData
	(*QueryUserListResp)(nil),   // 7: systemclient.QueryUserListResp
	(*LoginReq)(nil),            // 8: systemclient.LoginReq
	(*LoginResp)(nil),           // 9: systemclient.loginResp
	(*InfoReq)(nil),             // 10: systemclient.InfoReq
	(*InfoResp)(nil),            // 11: systemclient.InfoResp
	(*ReSetPasswordReq)(nil),    // 12: systemclient.ReSetPasswordReq
	(*ReSetPasswordResp)(nil),   // 13: systemclient.ReSetPasswordResp
}
var file_apps_admin_rpc_sys_proto_user_proto_depIdxs = []int32{
	6,  // 0: systemclient.QueryUserListResp.list:type_name -> systemclient.UserListData
	8,  // 1: systemclient.UserService.Login:input_type -> systemclient.LoginReq
	10, // 2: systemclient.UserService.UserInfo:input_type -> systemclient.InfoReq
	12, // 3: systemclient.UserService.ReSetPassword:input_type -> systemclient.ReSetPasswordReq
	9,  // 4: systemclient.UserService.Login:output_type -> systemclient.loginResp
	11, // 5: systemclient.UserService.UserInfo:output_type -> systemclient.InfoResp
	13, // 6: systemclient.UserService.ReSetPassword:output_type -> systemclient.ReSetPasswordResp
	4,  // [4:7] is the sub-list for method output_type
	1,  // [1:4] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_apps_admin_rpc_sys_proto_user_proto_init() }
func file_apps_admin_rpc_sys_proto_user_proto_init() {
	if File_apps_admin_rpc_sys_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_admin_rpc_sys_proto_user_proto_rawDesc), len(file_apps_admin_rpc_sys_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_admin_rpc_sys_proto_user_proto_goTypes,
		DependencyIndexes: file_apps_admin_rpc_sys_proto_user_proto_depIdxs,
		MessageInfos:      file_apps_admin_rpc_sys_proto_user_proto_msgTypes,
	}.Build()
	File_apps_admin_rpc_sys_proto_user_proto = out.File
	file_apps_admin_rpc_sys_proto_user_proto_goTypes = nil
	file_apps_admin_rpc_sys_proto_user_proto_depIdxs = nil
}
